# Generated by Django 5.1.2 on 2025-06-11 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InvoiceBoxApp', '0001_initial'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='CustomUser',
        ),
    ]
